RUBY_COMMAND = 'ruby' # was: 'ruby1.9.1'

def genpsalm_universal(zalm, options="", output_dir, input_dir)
  wd = Dir.pwd
  syrovy = input_dir+zalm
  peceny = output_dir+zalm.gsub(/\.pslm/, '')+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir output_dir
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def genpsalm(zalm, options="", output_dir='temporalia/', input_dir="../psalmi/")
  genpsalm_universal(zalm, options, output_dir, input_dir)
end

def genczechpsalm(zalm, options="", output_dir='temporalia/', input_dir="../bohemice_psalmi/Hejcl1922/")
  of = zalm.gsub(".pslm", "-boh.tex")
  ofop = "--output "+of+" "
  wd = Dir.pwd
  syrovy = input_dir+zalm
  of = zalm.gsub(".pslm", "-boh.tex")
  ofop = "--output "+of+" "
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file output_dir+of => [syrovy, preprocessor] do
    chdir output_dir
    sh "#{RUBY_COMMAND} #{preprocessor} #{ofop} #{options} ../#{syrovy}"
    chdir wd
  end
  return output_dir+of
end

def genzalmsuff(zalm, options="", suff="aaa", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'-'+suff+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} -o #{File.basename(peceny)} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def gregorio(srcf)
  f2 = srcf.gsub(".gabc", ".tex")
  file f2 => [srcf] do
    sh "gregorio #{srcf}"
  end
  return f2
end

def geninitium(psalm, tone, directory='temporalia/')
  ntone = tone
  if i = ntone.index('.') then
    ntone = ntone[0..i-1].downcase+'-'+ntone[i+1..-1]
  end
  patternfile = '../tonipsalmorum/arom12/'+ntone+'-auto.gabc'

  psalmfile = '../psalmi/' + (psalm.is_a?(Fixnum) ? "ps#{psalm}" : psalm) + '.pslm'
  
  i = File.basename(patternfile).index('.')
  output_ending = '-initium-'+File.basename(patternfile)[0..i-1]+'.gabc'
  outputfile = File.basename(psalmfile).gsub(/\.pslm$/, output_ending)

  file directory+outputfile => [psalmfile, patternfile, '../instrumenta/initiumpsalmi.rb'] do
    wd = Dir.pwd
    chdir directory
    sh "ruby ../../instrumenta/initiumpsalmi.rb ../#{psalmfile} ../#{patternfile}"
    chdir wd
  end

  return gregorio(directory+outputfile)
end

TONI_PSALMORUM = {
  'I.D' => [[2,0], [1,2]],
  'I.D2' => [[2,0], [1,2]],
  'Isoll.D2' => [[1,3], [1,2]],
  'II.D' => [[1,0], [1,1]],
  'III.a' => [[2,0], [1,1]],
  'IV.E' => [[1,2], [1,3]],
  'VI.F' => [[1,1], [1,2]],
  'VII.a' => [[2,0], [2,0]],
  'VII.c' => [[2,0], [2,0]],
  'VIII.G' => [[1,0], [1,2]],
  'VIIIsoll.G' => [[1,3], [1,2]],
  'per' => [[1,3], [1,1]],
  'dir' => [[1,2], [1,0]]
}

gloriapatri = File.readlines('../psalmi/gloriapatri.pslm').join ""

nativitas_psalmi = []

options_common = "--accents-style bold --append \"#{gloriapatri}\" --skip-verses 1 "
options_magnificat = options_common.gsub "--skip-verses 1", "--skip-verses 2"

options_translation = "--accents 0:0 --title-pattern \" \" --no-paragraph "

def options_accents(psalmtone)
  accents = "#{TONI_PSALMORUM[psalmtone][0][0]}:#{TONI_PSALMORUM[psalmtone][1][0]}"
  preps = "#{TONI_PSALMORUM[psalmtone][0][1]}:#{TONI_PSALMORUM[psalmtone][1][1]}"

  return "--accents #{accents} --preparatory-syllables #{preps}"
end

nativitas_cantus = []

# zalmy (akcenty podle napevu)
{62 => 'VI.F',
  66 => 'dir',
  92 => 'VIII.G',
  99 => 'VII.c',
  109 => 'VIII.G',
  112 => 'VII.c',
  121 => 'VI.F',
  126 => 'VIII.G',
  # 147 => 'VII.c',
  150 => 'VII.c'}.each_pair do |n,t|
  
  nativitas_psalmi << genpsalm("ps#{n}.pslm", options_common+options_accents(t))
  nativitas_psalmi << genczechpsalm("ps#{n}.pslm", options_translation)
  nativitas_cantus << geninitium(n, t)
end

# zalmy bez Gloria Patri
[148, 149].each do |n|
  nativitas_psalmi << genpsalm("ps#{n}.pslm", "--accents-style bold --skip-verses 1 "+options_accents('VII.c'))
  nativitas_psalmi << genczechpsalm("ps#{n}.pslm", options_translation)
  nativitas_cantus << geninitium(n, 'VII.c')
end

nativitas_psalmi << genpsalm('dan3.pslm', "--accents-style bold --skip-verses 1 "+options_accents('VIII.G'))
nativitas_cantus << geninitium('dan3', 'VIII.G')
nativitas_psalmi << genczechpsalm("dan3.pslm", options_translation, 'temporalia/', "../bohemice_psalmi/Pavlik/")

# Benedictus a Magnificat
nativitas_psalmi << genzalmsuff("magnificat.pslm", options_magnificat+options_accents('Isoll.D2'), 'iD2')
nativitas_psalmi << genzalmsuff("benedictus.pslm", options_common+options_accents('VIIIsoll.G'), 'viiiG')

nativitas_psalmi << genczechpsalm("magnificat.pslm", options_translation, 'temporalia/', "../bohemice_psalmi/DMC199x/")
nativitas_psalmi << genczechpsalm("benedictus.pslm", options_translation, 'temporalia/', "../bohemice_psalmi/DMC199x/")

# noty
["cantus/amon33/*.gabc", 
 "../cantuscommunes/triplex76/*.gabc", 
 "../cantuscommunes/kyriale76/*.gabc", 
 "../cantuscommunes/amon33/*.gabc"].each do |d|
  Dir[d].each do |s|
    nativitas_cantus << gregorio(s)
  end
end

# initium k Benedictus:
file "temporalia/benedictus-initium-viiiSoll-G-auto.gabc" => ["../psalmi/benedictus.pslm", "../tonipsalmorum/arom12/viiiSoll-G-auto.gabc", '../instrumenta/initiumpsalmi.rb'] do |t|
  psalmfile = t.prerequisites[0]
  patternfile = t.prerequisites[1]
  wd = Dir.pwd
  chdir "temporalia"
  sh "ruby ../../instrumenta/initiumpsalmi.rb ../#{psalmfile} ../#{patternfile}"
  chdir wd
end
nativitas_cantus << gregorio("temporalia/benedictus-initium-viiiSoll-G-auto.gabc")

nativitas_hymni = ['hym-AveMarisStella-text.tex', 
                   'hym-AveMarisStella-bohtext.tex',
                   'hym-OGloriosaDomina-text.tex'].collect {|h| 
  'cantus/amon33/'+h
}

file "innativitatebmv.pdf" => ['innativitatebmv.tex', 'translationes_cs.tex']+nativitas_cantus+nativitas_psalmi+nativitas_hymni do |t|
  # sh "xelatex #{t.prerequisites.first}"
  2.times { sh "lualatex -interaction=nonstopmode #{t.prerequisites.first}" }
end

file "supplementum.pdf" => ['supplementum.tex']+nativitas_cantus do |t|
  sh "lualatex -interaction=nonstopmode #{t.prerequisites.first}"
end

file "innativitate-neumae.pdf" => ["innativitatebmv.pdf", "paginaeneumatae/pg30-33-rotated.pdf"] do |t|
  # make a copy of the main output file with pages 30-33 replaced
  # by their scans containing neumes
  sh "pdfjoin --outfile #{t.name} #{t.prerequisites.first} '1-29' #{t.prerequisites[1]} '-' #{t.prerequisites.first} '34-'"
end

task :nativitas => ["innativitatebmv.pdf"]
task :nativitas_neumae => ["innativitate-neumae.pdf"]
task :supplementum => ["supplementum.pdf"]
task :default => [:nativitas]
