RUBY_COMMAND = 'ruby' # was: 'ruby1.9.1'

def genzalm(zalm, options="", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def genzalmsuff(zalm, options="", suff="aaa", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'-'+suff+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} -o #{File.basename(peceny)} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def gregorio(srcf)
  f2 = srcf.gsub(".gabc", ".tex")
  file f2 => [srcf] do
    sh "gregorio #{srcf}"
  end
  return f2
end

def geninitium(psalm, tone, directory='temporalia/')
  ntone = tone
  if i = ntone.index('.') then
    ntone = ntone[0..i-1].downcase+'-'+ntone[i+1..-1]
  end
  patternfile = '../tonipsalmorum/arom12/'+ntone+'-auto.gabc'

  psalmfile = '../psalmi/' + (psalm.is_a?(Fixnum) ? "ps#{psalm}" : psalm) + '.pslm'
  
  i = File.basename(patternfile).index('.')
  output_ending = '-initium-'+File.basename(patternfile)[0..i-1]+'.gabc'
  outputfile = File.basename(psalmfile).gsub(/\.pslm$/, output_ending)

  file directory+outputfile => [psalmfile, patternfile, '../instrumenta/initiumpsalmi.rb'] do
    wd = Dir.pwd
    chdir directory
    sh "ruby ../../instrumenta/initiumpsalmi.rb ../#{psalmfile} ../#{patternfile}"
    chdir wd
  end

  return gregorio(directory+outputfile)
end

TONI_PSALMORUM = {
  'I.D' => [[2,0], [1,2]],
  'I.D2' => [[2,0], [1,2]],
  'Isoll.D2' => [[1,3], [1,2]],
  'II.D' => [[1,0], [1,1]],
  'III.a' => [[2,0], [1,1]],
  'IV.E' => [[1,2], [1,3]],
  'VI.F' => [[1,1], [1,2]],
  'VII.a' => [[2,0], [2,0]],
  'VII.c' => [[2,0], [2,0]],
  'VIII.G' => [[1,0], [1,2]],
  'VIIIsoll.G' => [[1,3], [1,2]],
  'per' => [[1,3], [1,1]],
  'dir' => [[1,2], [1,0]]
}

gloriapatri = File.readlines('../psalmi/gloriapatri.pslm').join ""

nativitas_psalmi = []

options_common = "--accents-style bold --append \"#{gloriapatri}\" --skip-verses 1 "
options_magnificat = options_common.gsub "--skip-verses 1", "--skip-verses 2"

def options_accents(psalmtone)
  accents = "#{TONI_PSALMORUM[psalmtone][0][0]}:#{TONI_PSALMORUM[psalmtone][1][0]}"
  preps = "#{TONI_PSALMORUM[psalmtone][0][1]}:#{TONI_PSALMORUM[psalmtone][1][1]}"

  return "--accents #{accents} --preparatory-syllables #{preps}"
end

nativitas_cantus = []

# zalmy (akcenty podle napevu)
{62 => 'VI.F',
  66 => 'dir',
  92 => 'VIII.G',
  99 => 'VII.c',
  109 => 'VIII.G',
  112 => 'VII.c',
  121 => 'VI.F',
  126 => 'VIII.G',
  147 => 'VII.c',
  150 => 'VII.c'}.each_pair do |n,t|
  
  nativitas_psalmi << genzalm("ps#{n}.pslm", options_common+options_accents(t))
  nativitas_cantus << geninitium(n, t)
end

# zalmy bez Gloria Patri
[148, 149].each do |n|
  nativitas_psalmi << genzalm("ps#{n}.pslm", "--accents-style bold --skip-verses 1 "+options_accents('VII.c'))
  nativitas_cantus << geninitium(n, 'VII.c')
end

nativitas_psalmi << genzalm('dan3.pslm', "--accents-style bold --skip-verses 1 "+options_accents('VIII.G'))
nativitas_cantus << geninitium('dan3', 'VIII.G')

# Benedictus a Magnificat
nativitas_psalmi << genzalmsuff("magnificat.pslm", options_magnificat+options_accents('Isoll.D2'), 'iD2')
nativitas_psalmi << genzalmsuff("benedictus.pslm", options_common+options_accents('VIIIsoll.G'), 'viiiG')

# noty
Dir["cantus/amon33/*.gabc"].each do |s|
  nativitas_cantus << gregorio(s)
end
Dir["../cantuscommunes/amon33/*.gabc"].each do |s|
  nativitas_cantus << gregorio(s)
end

# initium k Benedictus:
file "temporalia/benedictus-initium-viiiSoll-G-auto.gabc" => ["../psalmi/benedictus.pslm", "../tonipsalmorum/arom12/viiiSoll-G-auto.gabc", '../instrumenta/initiumpsalmi.rb'] do |t|
  psalmfile = t.prerequisites[0]
  patternfile = t.prerequisites[1]
  wd = Dir.pwd
  chdir "temporalia"
  sh "ruby ../../instrumenta/initiumpsalmi.rb ../#{psalmfile} ../#{patternfile}"
  chdir wd
end
nativitas_cantus << gregorio("temporalia/benedictus-initium-viiiSoll-G-auto.gabc")

file "innativitatebmv.pdf" => ['innativitatebmv.tex']+nativitas_cantus+nativitas_psalmi do |t|
  # sh "xelatex #{t.prerequisites.first}"
  2.times { sh "lualatex -interaction=nonstopmode #{t.prerequisites.first}" }
end

task :nativitas => ["innativitatebmv.pdf"]
task :default => [:nativitas]
