RUBY_COMMAND = 'ruby' # was: 'ruby1.9.1'

def genzalm(zalm, options="", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def genzalmsuff(zalm, options="", suff="aaa", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'-'+suff+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} -o #{File.basename(peceny)} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

def gregorio(srcf)
  f2 = srcf.gsub(".gabc", ".tex")
  file f2 => [srcf] do
    sh "gregorio #{srcf}"
  end
  return f2
end

TONI_PSALMORUM = {
  'I.D' => [[2,0], [1,2]],
  'I.D2' => [[2,0], [1,2]],
  'II.D' => [[1,0], [1,1]],
  'III.a' => [[2,0], [1,1]],
  'IV.E' => [[1,2], [1,3]],
  'VI.F' => [[1,1], [1,2]],
  'VII.a' => [[2,0], [2,0]],
  'VII.c' => [[2,0], [2,0]],
  'VIII.G' => [[1,0], [1,2]],
  'per' => [[1,3], [1,1]],
  'dir' => [[1,2], [1,0]]
}

gloriapatri = File.readlines('../psalmi/gloriapatri.pslm').join ""

nativitas_psalmi = []

options_common = "--accents-style bold --append \"#{gloriapatri}\" "

def options_accents(psalmtone)
  accents = "#{TONI_PSALMORUM[psalmtone][0][0]}:#{TONI_PSALMORUM[psalmtone][1][0]}"
  preps = "#{TONI_PSALMORUM[psalmtone][0][1]}:#{TONI_PSALMORUM[psalmtone][1][1]}"

  return "--accents #{accents} --preparatory-syllables #{preps}"
end

# zalmy (akcenty podle napevu)
{62 => 'VI.F',
  66 => 'dir',
  92 => 'VIII.G',
  99 => 'VII.c',
  109 => 'VIII.G',
  112 => 'VII.c',
  121 => 'VI.F',
  126 => 'VIII.G',
  147 => 'VII.c'}.each_pair do |n,t|
  
  nativitas_psalmi << genzalm("ps#{n}.pslm", options_common+options_accents(t))
end

# Benedictus a Magnificat
nativitas_psalmi << genzalmsuff("magnificat.pslm", options_common+options_accents('I.D2'), 'iD2')
nativitas_psalmi << genzalmsuff("benedictus.pslm", options_common+options_accents('VIII.G'), 'viiiG')

nativitas_cantus = []
# antifony
1.upto(5) {|i|
  nativitas_cantus << gregorio("cantus/amon33/ant#{i}.gabc")
}
# napevy zalmu
Dir["../tonipsalmorum/arom12/*.gabc"].each {|t|
  nativitas_cantus << gregorio(t)
}
# hymny a spol
nativitas_cantus << gregorio("cantus/amon33/resp1v.gabc")
nativitas_cantus << gregorio("cantus/amon33/hym-AveMarisStella.gabc")
nativitas_cantus << gregorio("cantus/amon33/hym-OGloriosaDomina.gabc")
nativitas_cantus << gregorio("cantus/amon33/ant-magn-vesp1.gabc")
nativitas_cantus << gregorio("cantus/amon33/ant-ben-laud.gabc")
nativitas_cantus << gregorio("cantus/amon33/ant-magn-vesp2.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/deusinadiutorium-communis.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/supplicatiolitaniae.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/oratiodominica.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/dominusvobiscum-solemnis.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/domineexaudi.gabc")
nativitas_cantus << gregorio("../cantuscommunes/amon33/benedicamus-duplex-vesperae.gabc")

file "innativitatebmv.pdf" => ['innativitatebmv.tex']+nativitas_cantus+nativitas_psalmi do |t|
  # sh "xelatex #{t.prerequisites.first}"
  sh "lualatex -interaction=nonstopmode #{t.prerequisites.first}"
end

task :nativitas => ["innativitatebmv.pdf"]
task :default => [:nativitas]
