RUBY_COMMAND = 'ruby' # was: 'ruby1.9.1'

def genzalm(zalm, options="", adresar='temporalia/')
  wd = Dir.pwd
  syrovy = "../psalmi/"+zalm
  peceny = adresar+zalm.gsub(/\.pslm/, '')+'.tex'
  preprocessor = "/home/igneus/In-adiutorium/nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} ../#{syrovy}"
    chdir wd
  end
  return peceny
end

toni_psalmorum = {
  'I.D' => [[2,0], [1,2]],
  'I.D2' => [[2,0], [1,2]],
  'II.D' => [[1,0], [1,1]],
  'III.a' => [[2,0], [1,1]],
  'IV.E' => [[1,2], [1,3]],
  'VII.a' => [[2,0], [2,0]],
  'VII.c' => [[2,0], [2,0]],
  'VIII.G' => [[1,0], [1,2]],
  'per' => [[1,3], [1,1]]
}

nativitas_psalmi = []

{109 => 'VIII.G'}.each_pair do |n,t|
  accents = "#{toni_psalmorum[t][0][0]}:#{toni_psalmorum[t][1][0]}"
  preps = "#{toni_psalmorum[t][0][1]}:#{toni_psalmorum[t][1][1]}"
  nativitas_psalmi << genzalm("ps#{n}.pslm", "--accents-style bold --accents #{accents} --preparatory-syllables #{preps}")
end

file "innativitatebmv.pdf" => ['innativitatebmv.tex']+nativitas_psalmi do |t|
  sh "xelatex #{t.prerequisites.first}"
end

task :nativitas => ["innativitatebmv.pdf"]
